```{r}
fr_pondere_noESG <- subset(fr_pondere_noESG, select = -TreatmentPeriod.x
                         )

```


````{r}
# Utiliser la fonction left_join() de dplyr pour fusionner les dataframes
fr_pondere_ESG <- fr_pondere_ESG %>%
  group_by(id) %>%
  arrange(id, date) %>%
  mutate(Post = ifelse((FE_REVISION_EPS_REVDOWN > 1.5 * dplyr::lag(FE_REVISION_EPS_REVDOWN, default = first(FE_REVISION_EPS_REVDOWN)) & FE_REVISION_EPS_REVDOWN > 5 ) | (FE_REVISION_PRICE_TGT_REVDOWN > 1.5 * dplyr::lag(FE_REVISION_PRICE_TGT_REVDOWN, default = first(FE_REVISION_PRICE_TGT_REVDOWN)) & FE_REVISION_PRICE_TGT_REVDOWN > 5 ) , 1, 0))

  


# Trier la base de données par entreprise (id) et par date
fr_pondere_ESG <- fr_pondere_ESG %>% arrange(id, date)

# Regrouper les données par entreprise (id)
fr_pondere_ESG <- fr_pondere_ESG %>%
  group_by(id) %>%
  # Créer une nouvelle colonne pour indiquer si l'entreprise est traitée à partir de cette date
mutate(Post = ifelse(cummax(Post) == 1, 1, 0)) %>%
  ungroup()  


fr_pondere_ESG <- fr_pondere_ESG %>%
  group_by(id) %>%
  # Calcul de la période de traitement avec remplacement des NA par 0
  dplyr::summarise(TreatmentPeriod = ifelse(any(Post == 1), min(time[Post == 1], na.rm = TRUE), 0)) %>%
  # Fusion avec le dataframe original
  dplyr::left_join(fr_pondere_ESG, by = "id")


fr_pondere_ESG <- fr_pondere_ESG %>%
  group_by(id) %>%
  mutate(treated = ifelse(any(Post == 1), 1, 0)) %>%
  ungroup()


# Créer la colonne Group
fr_pondere_ESG <- fr_pondere_ESG %>%
  mutate(Group = paste("Group", TreatmentPeriod, sep = " "))
```




```{r}
# Estimer les paramètres DiD en utilisant une régression linéaire
diD_model <- lm(Outcome ~ Post + time + Post:time + Group - 1, data = fr_pondere_ESG)

# Extraire uniquement le coefficient estimé pour 'Post'
post_coefficient <- coef(diD_model)["Post"]

# Afficher le coefficient pour 'Post'
cat("Coefficient pour Post: ", post_coefficient, "\n")

```



````{r}
# Utiliser la fonction left_join() de dplyr pour fusionner les dataframes
fr_pondere_noESG <- fr_pondere_noESG %>%
  group_by(id) %>%
  arrange(id, date) %>%
  mutate(Post = ifelse((FE_REVISION_EPS_REVDOWN > 1.5 * dplyr::lag(FE_REVISION_EPS_REVDOWN, default = first(FE_REVISION_EPS_REVDOWN)) & FE_REVISION_EPS_REVDOWN > 5 ) | (FE_REVISION_PRICE_TGT_REVDOWN > 1.5 * dplyr::lag(FE_REVISION_PRICE_TGT_REVDOWN, default = first(FE_REVISION_PRICE_TGT_REVDOWN)) & FE_REVISION_PRICE_TGT_REVDOWN > 5 ) , 1, 0))

  


# Trier la base de données par entreprise (id) et par date
fr_pondere_noESG <- fr_pondere_noESG %>% arrange(id, date)

# Regrouper les données par entreprise (id)
fr_pondere_noESG <- fr_pondere_noESG %>%
  group_by(id) %>%
  # Créer une nouvelle colonne pour indiquer si l'entreprise est traitée à partir de cette date
mutate(Post = ifelse(cummax(Post) == 1, 1, 0)) %>%
  ungroup()  


fr_pondere_noESG <- fr_pondere_noESG %>%
  group_by(id) %>%
  # Calcul de la période de traitement avec remplacement des NA par 0
  dplyr::summarise(TreatmentPeriod = ifelse(any(Post == 1), min(time[Post == 1], na.rm = TRUE), 0)) %>%
  # Fusion avec le dataframe original
  dplyr::left_join(fr_pondere_noESG, by = "id")


fr_pondere_noESG <- fr_pondere_noESG %>%
  group_by(id) %>%
  mutate(treated = ifelse(any(Post == 1), 1, 0)) %>%
  ungroup()


# Créer la colonne Group
fr_pondere_noESG <- fr_pondere_noESG %>%
  mutate(Group = paste("Group", TreatmentPeriod, sep = " "))
```



```{r}
# Estimer les paramètres DiD en utilisant une régression linéaire
diD_model <- lm(Outcome ~ Post + time + Post:time + Group - 1, data = fr_pondere_noESG)

# Extraire uniquement le coefficient estimé pour 'Post'
post_coefficient <- coef(diD_model)["Post"]

# Afficher le coefficient pour 'Post'
cat("Coefficient pour Post: ", post_coefficient, "\n")
```




RAJOUT DE VARIABLES DE CONTROLE 

MERGED
```{r}
MarketData_All_Firms_in_ESG_Funds <- merge(MarketData_All_Firms_in_ESG_Funds, All_Unique_Companies, by=c("ticker"))
```


```{r}
MarketData_All_Firms_in_noESG_Funds <- merge(MarketData_All_Firms_in_noESG_Funds, All_Unique_Companies, by=c("ticker"))
```

```{r}
MarketData_All_Firms_in_ESG_Funds$date <- as.Date(as.character(MarketData_All_Firms_in_ESG_Funds$date), format="%Y%m%d")

MarketData_All_Firms_in_ESG_Funds$date <- format(MarketData_All_Firms_in_ESG_Funds$date, "%Y-%m-01")
```

```{r}
MarketData_All_Firms_in_noESG_Funds$date <- as.Date(as.character(MarketData_All_Firms_in_noESG_Funds$date), format="%Y%m%d")

MarketData_All_Firms_in_noESG_Funds$date <- format(MarketData_All_Firms_in_noESG_Funds$date, "%Y-%m-01")
```

```{r}
Market_ESG_cut  <- select(MarketData_All_Firms_in_ESG_Funds, date, isin, FE_VALUATION_PE_MEAN, P_PRICE, FREF_MARKET_VALUE_COMPANY, FE_REVISION_EPS_REVDOWN, FE_REVISION_PRICE_TGT_REVDOWN)
```

```{r}
Market_noESG_cut  <- select(MarketData_All_Firms_in_noESG_Funds, date, isin, FE_VALUATION_PE_MEAN, P_PRICE, FREF_MARKET_VALUE_COMPANY, FE_REVISION_EPS_REVDOWN, FE_REVISION_PRICE_TGT_REVDOWN )
```

```{r}
fr_cov_ESG <- merge(fond_representatif_filtré_ESG, Market_ESG_cut, by.x = c("id", "date"), by.y = c("isin", "date"))
```

```{r}
fr_cov_noESG <- merge(fond_representatif_filtré, Market_noESG_cut, by.x = c("id", "date"), by.y = c("isin", "date"))
```


DIFF AVEC VARIABLES DE CONTROLE
```{r}
# Estimer les paramètres DiD en utilisant une régression linéaire
diD_model <- lm(Outcome ~ Post + P_PRICE + FE_VALUATION_PE_MEAN + FREF_MARKET_VALUE_COMPANY + time + Post:time + Group - 1, data = fr_cov_noESG)

print(summary(diD_model))
```
