---
title: "Untitled"
output: html_document
date: "2024-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## 1. ESG


```{r}
selected_columns <- Covalence_AllData[, c("date", "CON_fina", "ESG_E", "CON_E", "Company", "ISIN", "GICS industry group", "Headquarters Region")]

# Créer une nouvelle base de données avec les colonnes sélectionnées
Covalence_reduite <- selected_columns
```
```{r}
ESG_All_reduite <- ESG_Funds_Holdings_All[, c("date", "fund_Isin", "market_value", "isin", "quantity")]
```

```{r}
ESG_All_reduite$date <- as.character(ESG_All_reduite$date)

# Utilisez substr() pour extraire l'année et le mois, et puis collez-les ensemble avec un tiret.
ESG_All_reduite$date <- paste(substr(ESG_All_reduite$date, 1, 4), substr(ESG_All_reduite$date, 5, 6), sep="-")
```

 
```{r}
merged_final <- merge(ESG_All_reduite, Covalence_reduite, by.x = c("isin", "date"), by.y = c("ISIN", "date"))
```

```{r}
merged_final$year <- as.integer(substr(as.character(merged_final$date), 1, 4))
merged_final$month <- as.integer(substr(merged_final$date, 6, 7))
```
```{r}
merged_final <- merged_final %>%
  rename(GICS_industry_group = `GICS industry group`)
```
```{r}
merged_final <- merged_final %>%
  rename(Headquarters_Region = `Headquarters Region`)
```

```{r}

# Tri du dataframe par Company, année et mois dans l'ordre décroissant
merged_final <- merged_final %>%
  arrange(Company, desc(year), desc(month))

# Sélectionner uniquement la première ligne de chaque combinaison de "Company" et "year"
merged_reduit <- merged_final %>%
  distinct(Company, year, .keep_all = TRUE)

```


```{r}

# Supposons que votre dataframe s'appelle last_month_data

# Agréger les données pour calculer la somme des valeurs de marché par année et secteur GICS
summary_data <- merged_reduit %>%
  group_by(year, GICS_industry_group) %>%
  summarise(total_market_value = sum(market_value)) %>%
  ungroup()

# Créer le graphique en utilisant ggplot2 avec des légendes plus petites
ggplot(summary_data, aes(x = factor(year), y = total_market_value, fill = GICS_industry_group)) +
  geom_bar(stat = "identity") +
  labs(x = "Année", y = "Total Market Value", title = "Répartition des Market Values par Secteur GICS pour Chaque Année (ESG)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  # Pour incliner les étiquettes de l'axe x pour une meilleure lisibilité
        legend.text = element_text(size = 6),  # Taille de texte de légende plus petite
        legend.title = element_text(size = 8))  # Taille de titre de légende plus petite


```


```{r}
# Ajouter une nouvelle colonne GICS_principal en fonction des conditions spécifiées
merged_reduit <- merged_reduit %>%
  mutate(GICS_principal = case_when(
    GICS_industry_group %in% c("Energy") ~ "Energy",
    GICS_industry_group %in% c("Materials") ~ "Materials",
    GICS_industry_group %in% c("Capital Goods", "Transportation", "Commercial & Professional Services") ~ "Industrials",
    GICS_industry_group %in% c("Consumer Services", "Consumer Discretionary Distribution & Retail", "Consumer Durables & Apparel", "Automobiles & Components") ~ "Consumer Discretionary",
    GICS_industry_group %in% c("Consumer Staples Distribution & Retail", "Food, Beverage & Tobacco", "Household & Personal Products") ~ "Consumer Staples",
    GICS_industry_group %in% c("Pharmaceuticals, Biotechnology & Life Sciences", "Health Care Equipment & Services") ~ "Health Care",
    GICS_industry_group %in% c("Financial Services", "Insurance", "Banks") ~ "Financials",
    GICS_industry_group %in% c("Software & Services", "Technology Hardware & Equipment", "Semiconductors & Semiconductor Equipment") ~ "Information & Technology",
    GICS_industry_group %in% c("Media & Entertainment", "Telecommunication Services") ~ "Communication Services",
    GICS_industry_group %in% c("Utilities") ~ "Utilities",
    GICS_industry_group %in% c("Equity Real Estate Investment Trusts (REITs)","Semiconductors & Semiconductor Equipment") ~ "Real Estate",
    TRUE ~ GICS_industry_group  # Garder la valeur d'origine si aucune des conditions ci-dessus n'est remplie
  ))

```

```{r}

# Agréger les données pour calculer la somme des valeurs de marché par année et secteur GICS
summary_data <- merged_reduit %>%
  group_by(year, GICS_principal) %>%
  summarise(total_market_value = sum(market_value)) %>%
  ungroup()

# Créer le graphique en utilisant ggplot2 avec des légendes plus petites
ggplot(summary_data, aes(x = factor(year), y = total_market_value, fill = GICS_principal)) +
  geom_bar(stat = "identity") +
  labs(x = "Année", y = "Total Market Value", title = "Répartition des Market Values par Secteur GICS pour Chaque Année (ESG)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  # Pour incliner les étiquettes de l'axe x pour une meilleure lisibilité
        legend.text = element_text(size = 6),  # Taille de texte de légende plus petite
        legend.title = element_text(size = 8))  # Taille de titre de légende plus petite


```


```{r}
summary_data_region <- merged_reduit %>%
  group_by(year, Headquarters_Region) %>%
  summarise(total_market_value = sum(market_value)) %>%
  ungroup()
```


```{r}
# Définir les couleurs souhaitées
couleurs <- c("orange", "indianred", "seagreen3", "plum1", "palegoldenrod")  # Par exemple, vous pouvez changer ces valeurs

# Créer le graphique en utilisant ggplot2 avec les couleurs modifiées
ggplot(summary_data_region, aes(x = factor(year), y = total_market_value, fill = Headquarters_Region)) +
  geom_bar(stat = "identity") +
  labs(x = "Année", y = "Total Market Value", title = "Répartition des Market Values par Région pour chaque année (ESG)") +
  scale_fill_manual(values = couleurs) +  # Spécifier les couleurs manuellement
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Pour incliner les étiquettes de l'axe x pour une meilleure lisibilité


```



## 2. Non ESG



```{r}
selected_columns_no_ESG <- Covalence_AllData[, c("date", "CON_fina", "ESG_E", "CON_E", "Company", "ISIN", "GICS industry group", "Headquarters Region")]

# Créer une nouvelle base de données avec les colonnes sélectionnées
Covalence_reduite_no_ESG <- selected_columns_no_ESG
```
```{r}
noESG_All_reduite <- noESG_Funds_Holdings_All[, c("date", "fund_Isin", "market_value", "isin", "quantity")]
```

```{r}
noESG_All_reduite$date <- as.character(noESG_All_reduite$date)

# Utilisez substr() pour extraire l'année et le mois, et puis collez-les ensemble avec un tiret.
noESG_All_reduite$date <- paste(substr(noESG_All_reduite$date, 1, 4), substr(noESG_All_reduite$date, 5, 6), sep="-")
```

 
```{r}
merged_final_no_ESG <- merge(noESG_All_reduite, Covalence_reduite_no_ESG, by.x = c("isin", "date"), by.y = c("ISIN", "date"))
```

```{r}
merged_final_no_ESG$year <- as.integer(substr(as.character(merged_final_no_ESG$date), 1, 4))
merged_final_no_ESG$month <- as.integer(substr(merged_final_no_ESG$date, 6, 7))
```
```{r}
merged_final_no_ESG <- merged_final_no_ESG %>%
  rename(GICS_industry_group = `GICS industry group`)
```
```{r}
merged_final_no_ESG <- merged_final_no_ESG %>%
  rename(Headquarters_Region = `Headquarters Region`)
```

```{r}

# Tri du dataframe par Company, année et mois dans l'ordre décroissant
merged_final_no_ESG <- merged_final_no_ESG %>%
  arrange(Company, desc(year), desc(month))

# Sélectionner uniquement la première ligne de chaque combinaison de "Company" et "year"
merged_reduit_no_ESG <- merged_final_no_ESG %>%
  distinct(Company, year, .keep_all = TRUE)

```


```{r}

# Agréger les données pour calculer la somme des valeurs de marché par année et secteur GICS
summary_data_no_ESG <- merged_reduit_no_ESG %>%
  group_by(year, GICS_industry_group) %>%
  summarise(total_market_value = sum(market_value)) %>%
  ungroup()

# Créer le graphique en utilisant ggplot2 avec des légendes plus petites
ggplot(summary_data_no_ESG, aes(x = factor(year), y = total_market_value, fill = GICS_industry_group)) +
  geom_bar(stat = "identity") +
  labs(x = "Année", y = "Total Market Value", title = "Répartition des Market Values par Secteur GICS pour Chaque Année (non ESG)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  # Pour incliner les étiquettes de l'axe x pour une meilleure lisibilité
        legend.text = element_text(size = 6),  # Taille de texte de légende plus petite
        legend.title = element_text(size = 8))  # Taille de titre de légende plus petite


```
```{r}
# Extraire tous les secteurs GICS distincts
secteurs_GICS <- unique(merged_reduit_no_ESG$GICS_industry_group)

# Afficher les secteurs GICS
print(secteurs_GICS)

```

```{r}
# Ajouter une nouvelle colonne GICS_principal en fonction des conditions spécifiées
merged_reduit_no_ESG <- merged_reduit_no_ESG %>%
  mutate(GICS_principal = case_when(
    GICS_industry_group %in% c("Energy") ~ "Energy",
    GICS_industry_group %in% c("Materials") ~ "Materials",
    GICS_industry_group %in% c("Capital Goods", "Transportation", "Commercial & Professional Services") ~ "Industrials",
    GICS_industry_group %in% c("Consumer Services", "Consumer Discretionary Distribution & Retail", "Consumer Durables & Apparel", "Automobiles & Components") ~ "Consumer Discretionary",
    GICS_industry_group %in% c("Consumer Staples Distribution & Retail", "Food, Beverage & Tobacco", "Household & Personal Products") ~ "Consumer Staples",
    GICS_industry_group %in% c("Pharmaceuticals, Biotechnology & Life Sciences", "Health Care Equipment & Services") ~ "Health Care",
    GICS_industry_group %in% c("Financial Services", "Insurance", "Banks") ~ "Financials",
    GICS_industry_group %in% c("Software & Services", "Technology Hardware & Equipment", "Semiconductors & Semiconductor Equipment") ~ "Information & Technology",
    GICS_industry_group %in% c("Media & Entertainment", "Telecommunication Services") ~ "Communication Services",
    GICS_industry_group %in% c("Utilities") ~ "Utilities",
    GICS_industry_group %in% c("Equity Real Estate Investment Trusts (REITs)","Semiconductors & Semiconductor Equipment") ~ "Real Estate",
    TRUE ~ GICS_industry_group  # Garder la valeur d'origine si aucune des conditions ci-dessus n'est remplie
  ))

```

```{r}

# Agréger les données pour calculer la somme des valeurs de marché par année et secteur GICS
summary_data_no_ESG <- merged_reduit_no_ESG %>%
  group_by(year, GICS_principal) %>%
  summarise(total_market_value = sum(market_value)) %>%
  ungroup()

# Créer le graphique en utilisant ggplot2 avec des légendes plus petites
ggplot(summary_data_no_ESG, aes(x = factor(year), y = total_market_value, fill = GICS_principal)) +
  geom_bar(stat = "identity") +
  labs(x = "Année", y = "Total Market Value", title = "Répartition des Market Values par Secteur GICS pour Chaque Année (non ESG)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  # Pour incliner les étiquettes de l'axe x pour une meilleure lisibilité
        legend.text = element_text(size = 6),  # Taille de texte de légende plus petite
        legend.title = element_text(size = 8))  # Taille de titre de légende plus petite


```





```{r}
# Agréger les données pour calculer la somme des valeurs de marché par année et secteur GICS
summary_data_region_no_ESG <- merged_reduit_no_ESG %>%
  group_by(year, Headquarters_Region) %>%
  summarise(total_market_value = sum(market_value)) %>%
  ungroup()


# Définir les couleurs souhaitées
couleurs <- c("orange", "indianred", "seagreen3", "plum1", "palegoldenrod")  # Par exemple, vous pouvez changer ces valeurs

# Créer le graphique en utilisant ggplot2 avec les couleurs modifiées
ggplot(summary_data_region_no_ESG, aes(x = factor(year), y = total_market_value, fill = Headquarters_Region)) +
  geom_bar(stat = "identity") +
  labs(x = "Année", y = "Total Market Value", title = "Répartition des Market Values par Région pour chaque année (nonESG)") +
  scale_fill_manual(values = couleurs) +  # Spécifier les couleurs manuellement
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Pour incliner les étiquettes de l'axe x pour une meilleure lisibilité


```







